# Generated by Django 4.1.3 on 2022-12-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.FloatField()),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='url',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='val',
            new_name='match',
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
