# Generated by Django 4.1.3 on 2022-12-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0002_score_rename_url_card_img_rename_val_card_match_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
